### ISSUE TITLE
Change foregroundColor based on %

### ISSUE THREAD

**Issue by Zzo911** [aarcoraci/javascript-fluid-meter#2]
Hi,

First, many thanks for sharing your code, this is exactly what I was look for.
I'm just wondering if it's possible to change the foregroundColor from JavaScript based on the %?
I tried the following without luck (water_level is my FluidMeter() which I change from JSON input) :
`if (myJSON.water_level > 75) water_level.backgroundColor = "#ff0000";`

Best regards

**Comment by aarcoraci** [comment]
hey, I'm glad you are using this project. I haven't touch it in a while. 
In order to achieve what you need to do I would suggest you fork this project and make some very small modification:
On the js-fluid-meter.js file just add the following method on the return:

```
    updateBackgroundColor(color){
      options.backgroundColor = color;
    }
```

You should place this just below the setPercentage method. It should look like this:
```
    setPercentage(percentage) {

      fillPercentage = clamp(percentage, 0, 100);
    },
    updateBackgroundColor(color){
      options.backgroundColor = color;
    }
```

I haven't test this but it should work. Basically when you need to update the color just call this method on the instance of your meter. Something like:
```
let meter =  = new FluidMeter();
meter.init(......);
meter.updateBackgroundColor("#ff0000'); 
```

Let me know if this doesn't work and as soon as I can I will be able to be more helpful.

**Comment by Zzo911** [comment]
Hi Angel,

Many thanks for your quick feedback, this is working as expected :)
I'm using this meter to display the water level of my rain tank from the web server of an ESP32, super awesome.

Best regards

**Comment by aarcoraci** [comment]
I'm really glad you found this useful. These projects are usually for me to practice and try to learn something new so finding out this helps someone really makes me feel happy.

Good luck Zzo911 !

**Comment by aarcoraci** [comment]
Hey, your comment motivated me to rewrite this library as an npm package. Just in case you need something more:
https://github.com/aarcoraci/fluid-meter

**Comment by Zzo911** [comment]
Hi,

I never used npm so I have to check so doc first.
The javascript version was easy to use :)
